// CommonJS, every file in node is a module (by default)
// Modules - Encapsulated code (only shar minimun)
const { john, peter } = require('./4-names')
const sayHi = require('./5-utils')
const data = require('./6-alternative-flavors')
require('./7-mind-grenade')

sayHi('susan')
sayHi(john)
sayHi(peter)
